### ISSUE TITLE
How can i upload more images to album?

### ISSUE THREAD

**Issue by bhushan-uzodocs** [rifaideen/humhub-modules-album#11]
Hi rifaideen, how can i upload more than one images to an album? Is there any way? Thanks!!
Great work!

**Comment by bhushan-uzodocs** [comment]
Hi rifaideen, how can upload more than one image to an album? Is there any way? Thanks!!

**Comment by rifaideen** [comment]
In album details page the options are provided. the individual album
details links are displayed in manage albums page.

**Comment by bhushan-uzodocs** [comment]
Thanks a lot! It works now!

**Comment by rifaideen** [comment]
welcome
