### ISSUE TITLE
URL Rewriting

### ISSUE THREAD

**Issue by abinadi** [rifaideen/humhub-modules-album#2]
The album module does not work if you are using clean URLs (as described here: https://github.com/humhub/humhub/blob/master/protected/docs/guide/administration/installation.md#enable-url-rewriting-optional

The problem, as far as I can tell, is that the url for viewing an album has the id as part of the uri instead of as a GET parameter. So you have this:
/album/view/id/1
Instead of this:
?r=album/update&id=1

In any case, it works when I set urlFormat to 'get' in the local/_settings.php config file, but it stops working when I set it to 'path'.

**Comment by rifaideen** [comment]
yes I have noticed now. they only written like that for path format.

**Comment by rifaideen** [comment]
Issue created on [humhub](https://github.com/humhub/humhub/issues/574) and will be resolved once they respond properly.

**Comment by rifaideen** [comment]
@abinadi this issue resolved.
