### ISSUE TITLE
Is this not compatible with the latest build of HumHub? 

### ISSUE THREAD

**Issue by WASasquatch** [rifaideen/humhub-modules-album#3]
It's riddled with errors and bugs on my HumHub i downloaded a couple days ago. I'm not sure why. For example, images on the Dashboard will open in the LIghtbox, but the thumbnail will be a broken image for starters. I'm not sure if this is a issue or just a version incompatibility.

**Comment by rifaideen** [comment]
When will be broken give the exact details

**Comment by WASasquatch** [comment]
When you post to your album, posts on your wall show a broken image until you click it and load it in Ekko Lightbox

When I create a "Album" i cannot enter it to add or upload any images. When I go back to the Album Config, no new albums show under the list. http://i.imgur.com/hniq4Lj.png

http://i.imgur.com/6LerLBZ.png All it does is show the album cover, no way to enter it to add images.

**Comment by rifaideen** [comment]
It is because of this folder uploads/album does not have write permission.
So make it write permission. If the album folder does not exist then create
it.

**Comment by rifaideen** [comment]
If you can't upload any image debug with firebug or see the response
returned by the server after upload.

**Comment by WASasquatch** [comment]
Images are uploading, this is on windows so no permissions to speak of on filesystem. They are not showing via lightbox, and the album is not explorable upon clicking it from the wall, only by viewing it directly which results in: http://i.imgur.com/LSl8PUb.jpg

**Comment by rifaideen** [comment]
you should check the whether images are uploaded or not. else give the
steps to reproduce the error. i will try to resolve it if time permitts

Thanks and regards
*- Rifaideen*

**Comment by WASasquatch** [comment]
They are there.

**Comment by rifaideen** [comment]
If you are developer I will accept your pull request once you fixed
yourself. because am also using windows system and I did not encountered
such error. may be you have deleted the files after uploading.

Thanks and regards
*- Rifaideen*

**Comment by WASasquatch** [comment]
May I ask what system you use for your server? Do you use ImageMagick? Do you assume safe URLs or is there a check? I have noticed Ekko Lightbox has issues with other images as well, particularily if "?cacheId=0" is added to the URI.

**Comment by rifaideen** [comment]
I did not used this on live server. I have checked this and developed on my
local system it was windows 8

Thanks and regards
*- Rifaideen*

**Comment by WASasquatch** [comment]
I mean what LAMP are you using? XAMPP, WAMP, other? Also see updates to post above.

**Comment by rifaideen** [comment]
XAMPP

Thanks and regards
*- Rifaideen*

**Comment by WASasquatch** [comment]
That may be why. I will try on a XAMPP server. They have horrible compatibility issues between it and a actual server.

**Comment by WASasquatch** [comment]
This may be why images aren't showing. Any reason we are not using full paths? http://i.imgur.com/e5ikEi1.png

**Comment by WASasquatch** [comment]
Again, also JS is broken for comments, cannot submit them

http://i.imgur.com/F75Boix.png

**Comment by rifaideen** [comment]
Look update your humhub now and in goto file settings page and add *Album*
for Hide file list widget from showing files for these objects on wall and
save. since this images are uploaded in different way you cant use the
default version.

Thanks and regards
*- Rifaideen*

**Comment by rifaideen** [comment]
by default humhub considers all files as private. but in album it is
considered as public so you cant use the default implementation to download
the file.

Thanks and regards
*- Rifaideen*

**Comment by WASasquatch** [comment]
HumHub is up to date. I have hide this information, and rebuilt cache, but the problem persists. Even the newly added direct link links to the same broken path and 404 page: http://i.imgur.com/diZ31xH.png

**Comment by rifaideen** [comment]
you should clearly understand one thing. you cannot download the files
uploaded for album using the showfiles widget ok. also do you have this
option on file setting *Hide file list widget from showing files for these
objects on wall.*

Thanks and regards
*- Rifaideen*

**Comment by WASasquatch** [comment]
I only have the options shown in the preview image. http://i.imgur.com/e9vFuBT.png

This happens when clicking images http://i.imgur.com/zDhfzv1.jpg

**Comment by rifaideen** [comment]
you system was too old. pull from the latest version from master that
includes merge pull request #538 <https://github.com/humhub/humhub/pull/538>
.

Thanks and regards
*- Rifaideen*

**Comment by rifaideen** [comment]
your dashboard must be like this once you updated
http://postimg.org/image/yoknmflph/

Thanks and regards
*- Rifaideen*

**Comment by WASasquatch** [comment]
Thank you I just found this on the master. For some reason from localhost, HumHub is not able to pull updates.

**Comment by rifaideen** [comment]
Is your case to do whatever you like also i dont have such issues since am
using the right way :)

Thanks and regards
*- Rifaideen*

**Comment by WASasquatch** [comment]
The right way is per the directions. As I am doing as well. Lol That was rude. You probably should add min-versions to your module, to really be doing it the right way. ;)

**Comment by rifaideen** [comment]
This module needs php 5.4+, current humhub. maybe partially work with
previous builds but using current build is required. and know issue it was
currently works well with get format url's path format url's having some
issues and was not answered properly by humhub community.

Thanks and regards
*- Rifaideen*

**Comment by WASasquatch** [comment]
You miss my point.

    "humhub": {
        "minVersion": "0.8.0"
    },

**Comment by rifaideen** [comment]
ok will do on next commit :)

Thanks and regards
*- Rifaideen*

**Comment by WASasquatch** [comment]
Thank you. Sorry for the trouble!

**Comment by rifaideen** [comment]
No is not a trouble. I will get back to you once I have tested this on my
testing server.

Thanks and regards
*- Rifaideen*

**Comment by WASasquatch** [comment]
Sounds good. I'm trying to figure out how to export my data from the old version of HumHub to the new one since it failed to update properly. Had to do a fresh install. Which is probably for the best, something was wrong.

**Comment by rifaideen** [comment]
you just use this command* git pull* is enough I think if you did not
changed any core files and modules.

Thanks and regards
*- Rifaideen*

**Comment by WASasquatch** [comment]
How would I edit the CSS by the way? I can't seem to get the edits to stick... I have edited the component.css but it still shows white despite black transparent colors.

**Comment by WASasquatch** [comment]
So upgraded to latest build and all that. The gallery is still having issues. Also how do you even navigate a gallery? There only seems to be the option to flip the image to the description. ..

Wall: http://i.imgur.com/gXzPyPB.jpg
Settings: http://i.imgur.com/S5YL747.png

**Comment by rifaideen** [comment]
I already told you that. You must  hide show file widget for Album it is
because of the album images are saved in a special way so you  cannot
download it from the url like this file/download.

**Comment by WASasquatch** [comment]
Please full read issues provided to you. As linked above: http://i.imgur.com/S5YL747.png

The module id is in the blacklist. It still persists.

**Comment by rifaideen** [comment]
Use Album not album. That settings is expected to be exact name of the
object. It is not module id.

**Comment by rifaideen** [comment]
You must add Album in the file settings menu under Hide file list widget from showing files for these objects on wall. note: object name is case sensitive. so give the exact object name.

**Comment by WASasquatch** [comment]
Thank you!
