### ISSUE TITLE
How do I add photos to an album?

### ISSUE THREAD

**Issue by Vatarus** [rifaideen/humhub-modules-album#4]
How do I add photos to an album?

**Comment by rifaideen** [comment]
Enable this module as admin and then goto your profile settings enable this
module then on your profile page you can see the link to create album. If
you cannot upload any images then check the uploads/album folder is
writable by server.

**Comment by Vatarus** [comment]
Well.
1. I created an album.
2. Add an album name and description.
3. Add the album cover (pic1, pic2).

How do I add photos to the album now?
No buttons to add photos to an album.
![00001](https://cloud.githubusercontent.com/assets/3394915/5986641/6e3af574-a944-11e4-8f6a-0521add9f0db.png)
![000002](https://cloud.githubusercontent.com/assets/3394915/5986642/6e3d9f04-a944-11e4-954e-99117af2d4ec.png)

**Comment by rifaideen** [comment]
Sorry for my late reply. go to profile -> album -> manage albums your albums are presented in gridview  click the details icon for the album you want to manage. then you can see the various menu related to the album.

**Comment by apollo13hk** [comment]
Dear Bro. 
I've download the code from 
https://github.com/rifaideen/humhub-modules-album
unzipped and plasted to \protected\modules\ 

and renamed the folder 'album' , but not understand how to start it ? any tips for me ??

**Comment by apollo13hk** [comment]
Dear Bro.
I've download the code from
https://github.com/rifaideen/humhub-modules-album
unzipped and plasted to \protected\modules\

and renamed the folder 'album' , but not understand how to start it ? any tips for me ??
