### ISSUE TITLE
Some album bug on the wall

### ISSUE THREAD

**Issue by Vatarus** [rifaideen/humhub-modules-album#5]
Found error in displaying links to the wall in browsers (IE11, Firefox 33).

![album_issue](https://cloud.githubusercontent.com/assets/3394915/6206515/2ab4d526-b5cf-11e4-8a20-e4ba88d15a6f.png)

**Comment by rifaideen** [comment]
Since the files uploaded by this module was public so it was uploaded and managed internally in a different manner so go to admin dashboard, file settings and add Album to the Hide file list widget text box.

**Comment by Vatarus** [comment]
Thanks! Good job!

**Comment by rifaideen** [comment]
update the module to latest commit

Thanks and regards
*- Rifaudeen*
