### ISSUE TITLE
creating a ajax chat

### ISSUE THREAD

**Issue by codinglover** [rifaideen/humhub-modules-album#6]
Hey it was really nice that you made a very nice module album. Can you make a chatroom module as well where users can chat with each other and can create chatroom as well. Admin can ban or kick them out of the chat etc ??? 

it would be really nice

**Comment by rifaideen** [comment]
No. the chat module was actually planned by humhub team. they will develop and release very soon.

**Comment by codinglover** [comment]
thanks for the quick reply brother...but humhub said they are not developing chat module

**Comment by rifaideen** [comment]
they are not developing now. but they have planned to do so in the future.

Thanks and regards
*- Rifaudeen*

**Comment by codinglover** [comment]
ok brother i am trying to code a simple chat using the wall format actually but stuck in automatically reload the page can you help me with it ? and also from the directory user profile posts page any way to add a pagination because its very long so the page would be very big when lot of messages added.
