### ISSUE TITLE
clicking on album redirect to dashboard

### ISSUE THREAD

**Issue by codinglover** [rifaideen/humhub-modules-album#7]
Hello brother, after installing and enable the module i set as always activated but when i click on album in my profile it redirect me to dashboard what could be the problem or how do i change these ?

**Comment by rifaideen** [comment]
As of now this module requires your application url schemes must use path format. so follow the steps in filesystem. open protected/config/_defaults.php and search for urlManager configuration and change urlFormat from get to path i.e 'urlFormat' => 'path'.

**Comment by rifaideen** [comment]
will be resolved on next commit.

**Comment by codinglover** [comment]
thanks brother it is working fine now but having another issue after uploading. While uploading the system is showing error of ID but the photo is adding fine.

when i am trying to edit it its showing : Unable to resolve the request "Email address/album/update/1".


any possible ways to give a tagging system to album photos that user can tag their friends in the photos

**Comment by rifaideen** [comment]
Thanks for reporting. this is fixed now. update your module.

Thanks and regards
*- Rifaudeen*
