### ISSUE TITLE
Error autostart.php

### ISSUE THREAD

**Issue by timvango** [rifaideen/humhub-modules-album#8]
Hi!

When I download this module, unzip it, upload it and rename the folder to album, it doesn't work.
My site doesn't show any errors, until I visit the Modules page. Then the whole site is unusable and gives the following error everywhere on the site until I remove the album folder.

The error is:
Parse error: syntax error, unexpected '[', expecting ')' in /home/***/public_html/protected/modules/album/autostart.php on line 3

I have enabled path format and I'm using HumHub version 0.10.1.

**Comment by rifaideen** [comment]
It looks like you are using php < 5.4 and this requirement was clearly
defined in the module requirements. so upgrade you php version to php 5.4
or higher and try.

Thanks and regards
*- Rifaudeen*
