### ISSUE TITLE
Wrong alias

### ISSUE THREAD

**Issue by Vatarus** [rifaideen/humhub-modules-album#9]
A get humhub error report:

Processing: exception 'CException' with message 'Wrong alias "album.components.AlbumUrlRule". Make sure it points to an existing directory or file.' in /var/www/html/protected/vendors/yii/YiiBase.php:347
Stack trace:
#0 /var/www/html/protected/vendors/yii/YiiBase.php(196): YiiBase::import('album.component...', true)
#1 /var/www/html/protected/vendors/yii/web/CUrlManager.php(301): YiiBase::createComponent(Array)
#2 /var/www/html/protected/vendors/yii/base/CApplication.php(543): CUrlManager->createUrl('user/profile', Array, '&')
#3 /var/www/html/protected/components/HConsoleApplication.php(88): CApplication->createUrl('user/profile', Array, '&')
#4 /var/www/html/protected/components/HConsoleApplication.php(105): HConsoleApplication->createUrl('user/profile', Array, '', '&')
#5 /var/www/html/themes/miafam/views/notification/notificationLayoutMail.php(38): HConsoleApplication->createAbsoluteUrl('user/profile', Array)
#6 /var/www/html/protected/vendors/yii/web/CBaseController.php(126): require('/var/www/html/t...')
#7 /var/www/html/protected/vendors/yii/web/CBaseController.php(95): CBaseController->renderInternal('/var/www/html/t...', Array, true)
#8 /var/www/html/protected/vendors/yii/web/widgets/CContentDecorator.php(76): CBaseController->renderFile('/var/www/html/t...', Array, true)
#9 /var/www/html/protected/vendors/yii/web/widgets/CContentDecorator.php(54): CContentDecorator->decorate('?<strong>??????...')
#10 /var/www/html/protected/vendors/yii/web/widgets/COutputProcessor.php(44): CContentDecorator->processOutput('?<strong>??????...')
#11 /var/www/html/protected/vendors/yii/web/CBaseController.php(206): COutputProcessor->run()
#12 /var/www/html/protected/vendors/yii/web/CBaseController.php(300): CBaseController->endWidget('CContentDecorat...')
#13 /var/www/html/protected/modules_core/comment/views/notifications/newComment_mail.php(13): CBaseController->endContent()
#14 /var/www/html/protected/vendors/yii/web/CBaseController.php(126): require('/var/www/html/p...')
#15 /var/www/html/protected/modules_core/notification/models/Notification.php(218): CBaseController->renderInternal('/var/www/html/p...', Array, true)
#16 /var/www/html/protected/commands/shell/EMailing/EMailing.php(153): Notification->getMailOut()
#17 /var/www/html/protected/commands/shell/EMailing/EMailing.php(70): EMailing->getNotificationContent(Object(User))
#18 /var/www/html/protected/commands/shell/ZCron/ZCronRunner.php(88): EMailing->run(Array)
#19 /var/www/html/protected/vendors/yii/console/CConsoleCommandRunner.php(71): ZCronRunner->run(Array)
#20 /var/www/html/protected/vendors/yii/console/CConsoleApplication.php(92): CConsoleCommandRunner->run(Array)
#21 /var/www/html/protected/vendors/yii/base/CApplication.php(180): CConsoleApplication->processRequest()
#22 /var/www/html/protected/yiic.php(26): CApplication->run()
#23 /var/www/html/protected/yiic(5): require_once('/var/www/html/p...')

**Comment by rifaideen** [comment]
Its impossible did you checked whether
modules/album/components/AlbumUrlRule.php exists

**Comment by rifaideen** [comment]
Thanks for reporting fixed.
